import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react';
import { getPriceInfo } from '../fetch';
import { Hours } from '../components/hours/hours';

const Home: NextPage = () => {
  const [priceInfo, setPriceInfo] = useState<IPriceInfo | undefined>(undefined)

  useEffect(() => {
    async function fetch() {
      const priceInfo = await getPriceInfo();
      setPriceInfo(priceInfo)    
    }

    fetch()
  }, [])

  if(!priceInfo){
    return null
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Hours priceInfo={priceInfo} />
      </main>
    </div>
  )
}

export default Home

function ViewerHomeQuery<T>(ViewerHomeQuery: any): { loading: any; error: any; data: any; } {
  throw new Error('Function not implemented.');
}
