import type { NextPage } from 'next'
import Head from 'next/head'
import { Periods } from '../components/periods/periods'
import { getPriceInfo } from '../fetch'

interface IProps {
    priceInfo: IPriceInfo | undefined
    lowestToday: string
    lowestTomorrow: string
}

const Home: NextPage<IProps> = ({ priceInfo, lowestToday, lowestTomorrow }) => {
    return (
        <div>
            <Head>
                <title>App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container mx-auto px-4">
                {lowestToday && <p> Billigaste idag: {lowestToday}</p>}
                {lowestTomorrow && <p> Billigast imorgon: {lowestTomorrow}</p>}
                {priceInfo && <Periods priceInfo={priceInfo} />}
            </main>
        </div>
    )
}

export async function getServerSideProps() {
    const priceInfo = await getPriceInfo()

    return { props: { priceInfo } }
}

export default Home
