import type { NextPage } from 'next'
import Head from 'next/head'
import { Periods } from '../components/periods/periods'
import { getPriceInfo } from '../fetch'

interface IProps {
    priceInfo: IPriceInfo | undefined
}

const Home: NextPage<IProps> = ({ priceInfo }) => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="container mx-auto px-4">
                {priceInfo && <Periods priceInfo={priceInfo} />}
            </main>
        </div>
    )
}

export async function getServerSideProps() {
    const priceInfo = await getPriceInfo()

    return { props: { priceInfo } }
}

export default Home
